# Generated by Django 4.2.6 on 2023-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="zipcode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
