# Generated by Django 4.2.6 on 2023-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Uzsakymas priimtas", "Uzsakymas priimtas"),
                    ("Paruosta siuntimui", "Paruosta siuntimui"),
                    ("Issiusta", "Issiusta"),
                    ("Pristatyta", "Atsaukta"),
                    ("Atsaukta", "Atsaukta"),
                ],
                default="Uzsakymas priimtas",
                max_length=50,
            ),
        ),
    ]
