# Generated by Django 4.2.6 on 2023-11-13 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0010_alter_wishlist_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderPlaced",
            new_name="Order",
        ),
    ]
